plugins {
  alias libs.plugins.jpi2
}

description = 'Febit LibCI Jenkins Support Plugin'

jenkinsPlugin {
  jenkinsVersion = "${libs.versions.jenkins.bom.get()}"
  homePage = uri("https://github.com/febit/febit-libci")
}

publish {
  onlyIf { false }
}

publishMavenArtifactPublicationToMavenRepository {
  onlyIf { false }
}

dependencies {
}
