/*
 * Copyright 2025-present febit.org (support@febit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.febit.libci.core.spec;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.UtilityClass;
import lombok.extern.jackson.Jacksonized;
import org.febit.lang.PeriodDuration;
import org.febit.libci.core.spec.support.SpecMapper;
import org.febit.libci.core.util.Immutables;
import org.jspecify.annotations.Nullable;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * Use artifacts to specify which files to save as job artifacts.
 * <p>
 * <a href="https://docs.gitlab.com/ci/yaml/#artifacts">...</a>
 *
 * @param name      Specify a unique name for every archive.
 *                  <p>
 *                  Defaults to 'artifacts', which becomes artifacts.zip when downloaded.
 * @param isPublic  Whether the job artifacts should be publicly available.
 *                  <p>
 *                  Defaults to true.
 * @param untracked Whether add all Git untracked files as artifacts (along with the paths defined in artifacts:paths).
 *                  <p>
 *                  NOTE: also matching artifacts in .gitignore are included.
 * @param when      Upload artifacts on job failure or despite the failure.
 * @param access    Determine who can access the job artifacts from the UI or API.
 * @param paths     Paths are relative to the project directory ($CI_PROJECT_DIR) and can’t directly link outside it.
 * @param exclude   Prevent files from being added to an artifact archive.
 * @param reports   Collect artifacts generated by included templates in jobs.
 * @param expireIn  Specify how long job artifacts are stored before they expire and are deleted.
 * @param exposeAs  Expose job artifacts in the merge request UI.
 *                  The expire_in setting does not affect:
 *                  + Artifacts from the latest job, unless keeping the latest job artifacts is disabled at the project level or instance-wide.
 *                  <p>
 *                  Ref: <a href="https://docs.gitlab.com/ci/jobs/job_artifacts/#link-to-job-artifacts-in-the-merge-request-ui">...</a>
 */
@Jacksonized
@lombok.Builder(
        builderClassName = "Builder"
)
@Expandable(phase = ExpandPhase.NESTED)
public record ArtifactsSpec(
        @Expandable(phase = ExpandPhase.RUN)
        @lombok.NonNull String name,

        @JsonProperty("public")
        @lombok.NonNull Boolean isPublic,
        @lombok.NonNull Boolean untracked,
        @lombok.NonNull When when,
        @lombok.NonNull Access access,

        @Expandable(phase = ExpandPhase.RUN)
        @lombok.NonNull List<String> paths,

        @Expandable(phase = ExpandPhase.RUN)
        @lombok.NonNull List<String> exclude,

        @Expandable(phase = ExpandPhase.RUN)
        @lombok.NonNull Map<ReportKind, Serializable> reports,

        @Nullable PeriodDuration expireIn,

        @Expandable(phase = ExpandPhase.RUN)
        @Nullable String exposeAs
) implements ISpec {

    public ArtifactsSpec {
        paths = Immutables.of(paths);
        exclude = Immutables.of(exclude);

        var copy = new LinkedHashMap<>(reports);
        copy.remove(null);
        copy.replaceAll((k, v) ->
                (Serializable) k.normalizer().apply(v)
        );
        reports = Collections.unmodifiableMap(copy);
    }

    @UtilityClass
    public static class Defaults {
        public static final String NAME = "artifacts";
        public static final Boolean IS_PUBLIC = true;
        public static final Boolean UNTRACKED = false;
        public static final When WHEN = When.ON_SUCCESS;
        public static final Access ACCESS = Access.ALL;
        public static final List<String> PATHS = List.of();
        public static final List<String> EXCLUDE = List.of();
        public static final Map<ReportKind, Serializable> REPORTS = Map.of();
    }

    public static class Builder {

        @JsonCreator
        public Builder() {
            name(Defaults.NAME);
            isPublic(Defaults.IS_PUBLIC);
            untracked(Defaults.UNTRACKED);
            when(Defaults.WHEN);
            access(Defaults.ACCESS);
            paths(Defaults.PATHS);
            exclude(Defaults.EXCLUDE);
            reports(Defaults.REPORTS);
        }
    }

    @Getter
    @RequiredArgsConstructor
    public enum Access {
        ALL("all",
                "Artifacts in a job in public pipelines are available for download by anyone,"
                        + " including anonymous, guest, and reporter users."
        ),
        DEVELOPER("developer",
                "Artifacts in the job are only available for download by users with the Developer role or higher."
        ),
        NONE("none",
                "Artifacts in the job are not available for download by anyone."
        ),
        ;

        @JsonValue
        private final String value;
        private final String description;
    }

    @Getter
    @RequiredArgsConstructor
    public enum When {
        ALWAYS("always",
                "Always upload artifacts (except when jobs time out)."
        ),
        ON_SUCCESS("on_success",
                "Upload artifacts only when the job succeeds."
        ),
        ON_FAILURE("on_failure",
                "Upload artifacts only when the job fails."
        ),
        ;

        @JsonValue
        private final String value;
        private final String description;

        public boolean isAlways() {
            return this == ALWAYS;
        }

        public boolean isOnSuccess() {
            return this == ON_SUCCESS;
        }

        public boolean isOnFailure() {
            return this == ON_FAILURE;
        }
    }

    @Getter
    @Accessors(fluent = true)
    @RequiredArgsConstructor
    public enum ReportKind {
        ACCESSIBILITY("accessibility",
                "Uses pa11y to report on the accessibility impact of changes introduced in merge requests.",
                ReportFactories::string),
        ANNOTATIONS("annotations",
                "Used to attach auxiliary data to a job.",
                ReportFactories::string),
        API_FUZZING("api_fuzzing",
                "collects API Fuzzing bugs as artifacts",
                ReportFactories::unknown),
        BROWSER_PERFORMANCE("browser_performance",
                "Collects Browser Performance Testing metrics as an artifact.",
                ReportFactories::stringList),
        COVERAGE_REPORT("coverage_report",
                " collect coverage report in Cobertura or JaCoCo formats.",
                ReportFactories.mapper(CoverageReport.class)),
        CODE_QUALITY("codequality",
                "collects code quality issues.",
                ReportFactories::stringList),
        CONTAINER_SCANNING("container_scanning",
                "Collects Container Scanning vulnerabilities.",
                ReportFactories::stringList),
        COVERAGE_FUZZING("coverage_fuzzing",
                "collects coverage fuzzing bugs.",
                ReportFactories::stringList),
        CYCLONEDX("cyclonedx",
                "Software Bill of Materials describing the components of a project following the CycloneDX protocol format.",
                ReportFactories::stringList),
        DAST("dast",
                "DAST vulnerabilities",
                ReportFactories::stringList),
        DEPENDENCY_SCANNING("dependency_scanning",
                "Dependency Scanning vulnerabilities. ",
                ReportFactories::stringList),

        // https://docs.gitlab.com/ci/yaml/artifacts_reports/#artifactsreportsdotenv
        DOTENV("dotenv",
                "Collects a set of environment variables as artifacts",
                ReportFactories::stringList),

        JUNIT("junit",
                "JUnit report format XML files",
                ReportFactories::stringList),
        LOAD_PERFORMANCE("load_performance",
                "Load Performance Testing metrics",
                ReportFactories::stringList),
        METRICS("metrics",
                "Metrics",
                ReportFactories::stringList),
        REQUIREMENTS("requirements",
                "requirements.json files",
                ReportFactories::stringList),
        SAST("sast",
                "SAST vulnerabilities.",
                ReportFactories::stringList),
        SECRET_DETECTION("secret_detection",
                "detected secrets",
                ReportFactories::stringList),
        TERRAFORM("terraform",
                "obtains an OpenTofu tfplan.json file.",
                ReportFactories::stringList);

        @JsonValue
        private final String value;
        private final String description;
        private final Function<@Nullable Object, ? extends @Nullable Serializable> normalizer;
    }

    public interface IReport extends ISpec {
    }

    @UtilityClass
    private static class ReportFactories {

        @Nullable
        static Serializable unknown(@Nullable Object obj) {
            return (Serializable) obj;
        }

        @SuppressWarnings("SameParameterValue")
        static <R extends @Nullable IReport> Function<@Nullable Object, R> mapper(Class<R> type) {
            return obj -> obj == null ? null
                    : SpecMapper.toBean(obj, type);
        }

        static ArrayList<String> stringList(@Nullable Object obj) {
            if (obj == null) {
                return new ArrayList<>();
            }
            return SpecMapper.toStringList(obj);
        }

        @Nullable
        static String string(@Nullable Object obj) {
            if (obj == null) {
                return null;
            }
            return obj.toString();
        }
    }

    /**
     * Coverage report.
     * <p>
     * Ref: <a href="https://docs.gitlab.com/ci/yaml/artifacts_reports/#artifactsreportscoverage_report">...</a>
     */
    @Jacksonized
    @lombok.Builder(
            builderClassName = "Builder"
    )
    @Expandable(phase = ExpandPhase.NESTED)
    public record CoverageReport(
            Format coverageFormat,
            @Expandable(phase = ExpandPhase.RUN)
            String path
    ) implements IReport {

        @Getter
        @RequiredArgsConstructor
        public enum Format {
            COBERTURA("cobertura"),
            JACOCO("jacoco"),
            ;

            @JsonValue
            private final String value;
        }
    }
}
