/*
 * Copyright 2025-present febit.org (support@febit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.febit.libci.core.predefined;

import org.febit.libci.core.variable.IDefined;
import org.febit.libci.core.variable.VarDefinedPhase;

import lombok.RequiredArgsConstructor;
import lombok.experimental.Accessors;

import static org.febit.libci.core.variable.VarDefinedPhase.DEFINED_WORKFLOW;
import static org.febit.libci.core.variable.VarDefinedPhase.LIBCI_CONST;
import static org.febit.libci.core.variable.VarDefinedPhase.PERSISTED_JOB;
import static org.febit.libci.core.variable.VarDefinedPhase.PERSISTED_PIPELINE;
import static org.febit.libci.core.variable.VarDefinedPhase.PREDEFINED_JOB;
import static org.febit.libci.core.variable.VarDefinedPhase.PREDEFINED_SCM;
import static org.febit.libci.core.variable.VarDefinedPhase.PREDEFINED_SYS;
import static org.febit.libci.core.variable.VarDefinedPhase.RUNTIME_ENV;
import static org.febit.libci.core.variable.VarDefinedPhase.UNDEFINED;

/**
 * <a href="https://docs.gitlab.com/ci/variables/predefined_variables/">predefined_variables</a>
 */
@Accessors(fluent = true)
@RequiredArgsConstructor
public enum Predefined implements IDefined {

    GITLAB_CI(PREDEFINED_SYS),
    KUBE_NAMESPACE(RUNTIME_ENV),
    RUNNERS_SHARED_ENABLED(PREDEFINED_SYS),

    CI(LIBCI_CONST),
    CI_DEBUG_SERVICES(UNDEFINED),
    CI_DEBUG_TRACE(UNDEFINED),

    CI_CONFIG_PATH(PERSISTED_PIPELINE),
    CI_CONFIG_REF_URI(PERSISTED_PIPELINE),

    CI_CONCURRENT_ID(PREDEFINED_SYS),
    CI_CONCURRENT_PROJECT_ID(PREDEFINED_SYS),

    CI_DISPOSABLE_ENVIRONMENT(PREDEFINED_SYS),

    CI_KUBERNETES_ACTIVE(PREDEFINED_SYS),

    CI_ENVIRONMENT_ACTION(PREDEFINED_SYS),
    CI_ENVIRONMENT_ID(PREDEFINED_SYS),
    CI_ENVIRONMENT_NAME(PREDEFINED_SYS),
    CI_ENVIRONMENT_SLUG(PREDEFINED_SYS),
    CI_ENVIRONMENT_TIER(PREDEFINED_SYS),
    CI_ENVIRONMENT_URL(PREDEFINED_SYS),

    CI_BUILDS_DIR(PERSISTED_JOB),

    CI_JOB_GROUP_NAME(PREDEFINED_JOB),
    CI_JOB_ID(PREDEFINED_JOB),
    CI_JOB_IMAGE(PREDEFINED_JOB),
    CI_JOB_MANUAL(PREDEFINED_JOB),
    CI_JOB_NAME(PREDEFINED_JOB),
    CI_JOB_NAME_SLUG(PREDEFINED_JOB),
    CI_JOB_STAGE(PREDEFINED_JOB),
    CI_JOB_STARTED_AT(PREDEFINED_JOB),
    CI_JOB_STARTED_AT_SLUG(PREDEFINED_JOB),
    CI_JOB_STATUS(PREDEFINED_JOB),
    CI_JOB_TIMEOUT(PREDEFINED_JOB),
    CI_JOB_TOKEN(PREDEFINED_JOB),
    CI_JOB_URL(PREDEFINED_JOB),

    CI_NODE_INDEX(PREDEFINED_JOB),
    CI_NODE_TOTAL(PREDEFINED_JOB),

    CI_COMMIT_AUTHOR(PREDEFINED_SCM),
    CI_COMMIT_AUTHOR_EMAIL(PREDEFINED_SCM),
    CI_COMMIT_AUTHOR_NAME(PREDEFINED_SCM),
    CI_COMMIT_BEFORE_SHA(PREDEFINED_SCM),
    CI_COMMIT_BRANCH(PREDEFINED_SCM),
    CI_COMMIT_DESCRIPTION(PREDEFINED_SCM),
    CI_COMMIT_MESSAGE(PREDEFINED_SCM),
    CI_COMMIT_REF_NAME(PREDEFINED_SCM),
    CI_COMMIT_REF_PROTECTED(PREDEFINED_SCM),
    CI_COMMIT_REF_SLUG(PREDEFINED_SCM),
    CI_COMMIT_SHA(PREDEFINED_SCM),
    CI_COMMIT_SHORT_SHA(PREDEFINED_SCM),
    CI_COMMIT_TAG(PREDEFINED_SCM),
    CI_COMMIT_TIMESTAMP(PREDEFINED_SCM),
    CI_COMMIT_TITLE(PREDEFINED_SCM),

    CI_DEFAULT_BRANCH(PREDEFINED_SCM),
    CI_DEFAULT_BRANCH_SLUG(PREDEFINED_SCM),

    CI_MERGE_REQUEST_APPROVED(PREDEFINED_SCM),
    CI_MERGE_REQUEST_ASSIGNEES(PREDEFINED_SCM),
    CI_MERGE_REQUEST_DESCRIPTION(PREDEFINED_SCM),
    CI_MERGE_REQUEST_DESCRIPTION_IS_TRUNCATED(PREDEFINED_SCM),
    CI_MERGE_REQUEST_DIFF_BASE_SHA(PREDEFINED_SCM),
    CI_MERGE_REQUEST_DIFF_ID(PREDEFINED_SCM),
    CI_MERGE_REQUEST_DRAFT(PREDEFINED_SCM),
    CI_MERGE_REQUEST_EVENT_TYPE(PREDEFINED_SCM),
    CI_MERGE_REQUEST_ID(PREDEFINED_SCM),
    CI_MERGE_REQUEST_IID(PREDEFINED_SCM),
    CI_MERGE_REQUEST_LABELS(PREDEFINED_SCM),
    CI_MERGE_REQUEST_MILESTONE(PREDEFINED_SCM),
    CI_MERGE_REQUEST_PROJECT_ID(PREDEFINED_SCM),
    CI_MERGE_REQUEST_PROJECT_PATH(PREDEFINED_SCM),
    CI_MERGE_REQUEST_PROJECT_URL(PREDEFINED_SCM),
    CI_MERGE_REQUEST_REF_PATH(PREDEFINED_SCM),
    CI_MERGE_REQUEST_SOURCE_BRANCH_NAME(PREDEFINED_SCM),
    CI_MERGE_REQUEST_SOURCE_BRANCH_PROTECTED(PREDEFINED_SCM),
    CI_MERGE_REQUEST_SOURCE_BRANCH_SHA(PREDEFINED_SCM),
    CI_MERGE_REQUEST_SOURCE_PROJECT_ID(PREDEFINED_SCM),
    CI_MERGE_REQUEST_SOURCE_PROJECT_PATH(PREDEFINED_SCM),
    CI_MERGE_REQUEST_SOURCE_PROJECT_URL(PREDEFINED_SCM),
    CI_MERGE_REQUEST_SQUASH_ON_MERGE(PREDEFINED_SCM),
    CI_MERGE_REQUEST_TARGET_BRANCH_NAME(PREDEFINED_SCM),
    CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED(PREDEFINED_SCM),
    CI_MERGE_REQUEST_TARGET_BRANCH_SHA(PREDEFINED_SCM),
    CI_MERGE_REQUEST_TITLE(PREDEFINED_SCM),

    CI_PROJECT_CLASSIFICATION_LABEL(PREDEFINED_SCM),
    CI_PROJECT_DESCRIPTION(PREDEFINED_SCM),
    CI_PROJECT_DIR(PREDEFINED_JOB),
    CI_PROJECT_ID(PREDEFINED_SCM),
    CI_PROJECT_NAME(PREDEFINED_SCM),
    CI_PROJECT_NAMESPACE(PREDEFINED_SCM),
    CI_PROJECT_NAMESPACE_ID(PREDEFINED_SCM),
    CI_PROJECT_NAMESPACE_SLUG(PREDEFINED_SCM),
    CI_PROJECT_PATH(PREDEFINED_SCM),
    CI_PROJECT_PATH_SLUG(PREDEFINED_SCM),
    CI_PROJECT_REPOSITORY_LANGUAGES(PREDEFINED_SCM),
    CI_PROJECT_ROOT_NAMESPACE(PREDEFINED_SCM),
    CI_PROJECT_ROOT_NAMESPACE_SLUG(PREDEFINED_SCM),
    CI_PROJECT_TITLE(PREDEFINED_SCM),
    CI_PROJECT_TOPICS(PREDEFINED_SCM),
    CI_PROJECT_URL(PREDEFINED_SCM),
    CI_PROJECT_VISIBILITY(PREDEFINED_SCM),

    CI_REPOSITORY_URL(PREDEFINED_SCM),

    CI_API_GRAPHQL_URL(PREDEFINED_SYS),
    CI_API_V4_URL(PREDEFINED_SYS),

    CI_PIPELINE_CREATED_AT(PREDEFINED_SYS),
    CI_PIPELINE_ID(PREDEFINED_SYS),
    CI_PIPELINE_IID(PREDEFINED_SYS),
    CI_PIPELINE_NAME(DEFINED_WORKFLOW),
    CI_PIPELINE_SCHEDULE_DESCRIPTION(PREDEFINED_SYS),
    CI_PIPELINE_SOURCE(PREDEFINED_SYS),
    CI_PIPELINE_TRIGGERED(PREDEFINED_SYS),
    CI_PIPELINE_URL(PREDEFINED_SYS),

    CI_RUNNER_DESCRIPTION(PREDEFINED_SYS),
    CI_RUNNER_EXECUTABLE_ARCH(PREDEFINED_SYS),
    CI_RUNNER_ID(PREDEFINED_SYS),
    CI_RUNNER_REVISION(PREDEFINED_SYS),
    CI_RUNNER_SHORT_TOKEN(PREDEFINED_SYS),
    CI_RUNNER_TAGS(PREDEFINED_SYS),
    CI_RUNNER_VERSION(PREDEFINED_SYS),

    CI_SERVER(PREDEFINED_JOB),
    CI_SERVER_FQDN(PREDEFINED_SYS),
    CI_SERVER_HOST(PREDEFINED_SYS),
    CI_SERVER_NAME(PREDEFINED_SYS),
    CI_SERVER_PORT(PREDEFINED_SYS),
    CI_SERVER_PROTOCOL(PREDEFINED_SYS),
    CI_SERVER_REVISION(PREDEFINED_SYS),
    CI_SERVER_SHELL_SSH_HOST(PREDEFINED_SYS),
    CI_SERVER_SHELL_SSH_PORT(PREDEFINED_SYS),
    CI_SERVER_TLS_CA_FILE(PREDEFINED_SYS),
    CI_SERVER_TLS_CERT_FILE(PREDEFINED_SYS),
    CI_SERVER_TLS_KEY_FILE(PREDEFINED_SYS),
    CI_SERVER_URL(PREDEFINED_SYS),
    CI_SERVER_VERSION(PREDEFINED_SYS),
    CI_SERVER_VERSION_MAJOR(PREDEFINED_SYS),
    CI_SERVER_VERSION_MINOR(PREDEFINED_SYS),
    CI_SERVER_VERSION_PATCH(PREDEFINED_SYS),
    ;

    @lombok.Getter
    private final VarDefinedPhase phase;
}
